# Enable mouse scrollback
set -g mouse on
set -g base-index 1

set -g default-terminal "tmux-256color"
# tell Tmux that outside terminal supports true color
set -ga terminal-overrides ",Alacritty*:Tc"

# don't rename windows automatically
set -g allow-rename off
setw -g pane-base-index 1
setw -g mode-keys vi

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind t split-window -v -c "#{pane_current_path}" -p 35
unbind '"'
unbind %

set-option -sg escape-time 0

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch panes using Alt-arrow without prefix
bind -n M-l select-pane -L
bind -n M-h select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

bind -n M-0 select-window -t 0
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind a set-option -g status

# default statusbar color
set-option -g status-style bg=colour238,fg=colour194 # bg=bg1, fg=fg1

# pane border
set-option -g pane-active-border-style fg=colour230 #fg2
set-option -g pane-border-style fg=colour238 #bg1

# message infos
set-option -g message-style bg=colour239,fg=colour223 # bg=bg2, fg=fg1

# writing commands inactive
set-option -g message-command-style bg=colour239,fg=colour223 # bg=fg3, fg=bg1

set-window-option -g window-status-current-format "#[bg=colour250,fg=colour238,bold]  #I #[bg=colour250,fg=red,bold]#{?window_zoomed_flag,*Z,} "
set-window-option -g window-status-format "#[bg=colour239,fg=colour230,bold]  #I  "

set -g status-interval 10
set -g status-left "[#[fg=colour222,bg=colour239] %H:%M #[fg=colour230,bg=colour239]]|"
set -g status-right "#{host} "
set -g status-right-length 80
set -g status-right-style default
set -g status-style fg=colour230,bg=colour239
